### ISSUE TITLE
Missing Model: "SignalResponseSuspectScore"

### ISSUE THREAD

**Issue by SergkeiM** [fingerprintjs/fingerprint-pro-server-api-php-sdk#86]
FingerPrint has a new property `suspectScore`

![image](https://github.com/fingerprintjs/fingerprint-pro-server-api-php-sdk/assets/3294939/d7308786-3229-4edf-aec5-47e6e985bf01)

PHP SDK is missing `SignalResponseSuspectScore` Model.

**Comment by makma** [comment]
Hey @SergkeiM , yes, the `suspectScore` is quite a new feature, we're working on adding it to the SDK.

**Comment by ilfa** [comment]
Hey @SergkeiM!
You can try [v4.0.0](https://github.com/fingerprintjs/fingerprint-pro-server-api-php-sdk/releases/tag/v4.0.0) now.
