### ISSUE TITLE
Class VpnResultMethods is missing osMismatch

### ISSUE THREAD

**Issue by manuel-watchenterprise** [fingerprintjs/fingerprint-pro-server-api-php-sdk#97]
The [VpnResultMethods](https://github.com/fingerprintjs/fingerprint-pro-server-api-php-sdk/blob/main/src/Model/VpnResultMethods.php) class does not include / handle `osMismatch` data which, however, exists in API response. This way, the information is lost and is not accessible as the class stores in its container only those properties that are known.

Original JSON response:
```json
{
  "vpn": {
    "data": {
      "result": false,
      "originTimezone": "Europe/Budapest",
      "originCountry": "unknown",
      "methods": {
        "timezoneMismatch": false,
        "publicVPN": false,
        "auxiliaryMobile": false,
        "osMismatch": false
      }
    }
  }
}
```

**Comment by Orkuncakilkaya** [comment]
Hey @manuel-watchenterprise 👋 
This will be released in the following major Fingerprint Pro Server API PHP SDK release.

**Comment by Orkuncakilkaya** [comment]
With [version 5.0.0](https://github.com/fingerprintjs/fingerprint-pro-server-api-php-sdk/releases/tag/v5.0.0), you can get VPN signals like this
```php
/** @var \Fingerprint\ServerAPI\Model\EventResponse $result */
list($result, $response) = $client->getEvent($request_id);

$vpnResult = $result->getProducts()->getVpn()->getData()->getResult();
```
